"use strict";
let cities = ["Newyork", "Paris", "London", "Moscow", "Goa"];
console.log(cities);
console.log(cities.slice().sort());
console.log(cities);
console.log(cities.slice().reverse());
console.log(cities);
console.log(cities.reverse());
console.log(cities);
console.log(cities.sort());
console.log(cities.reverse());
