"use strict";
let a = 10;
console.log(a == 10);
let upp = "AHMED";
let low = "ahmed";
console.log(upp === low);
let b = 10;
let c = 10;
console.log(b === c);
console.log(b !== c);
console.log(b < c);
console.log(b > c);
console.log(b <= c);
console.log(b >= c);
let name2 = true;
let name1 = false;
console.log(name1 && name2);
let bol = true;
let bol1 = false;
console.log(bol || bol1);
let ary = ["Ahmed", "Ebad", "Anas"];
console.log(ary[0] === "Ahmed");
console.log(ary[1] === "Ahmed");
